import os


FLASK_SECRET_KEY = os.environ['FLASK_SECRET_KEY']
S3_BUCKET = os.environ['S3_BUCKET']
DROPBOX_APP_KEY = os.environ['DROPBOX_APP_KEY']
DROPBOX_APP_SECRET = os.environ['DROPBOX_APP_SECRET']
DROPBOX_TOKEN = os.environ['DROPBOX_TOKEN']
DROPBOX_ROOT = os.environ['DROPBOX_ROOT']
AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
